---
# This playbook deploys a simple standalone JBoss server. 

- hosts: all
  tasks:
    - name: install git, docker, tmux, emacs
      yum: name=git,docker,tmux,emacs state=latest

    - name: install vagrant from rpm
      yum: name=https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.rpm state=present

    - name: add ec2-user to docker
      user: name=ec2-user groups=docker append=yes

    - name: add test users
      user: name={{ item.1 }} shell=/bin/bash state=present group=ec2-user groups=docker uid={{ item.0 + 520}}
      with_indexed_items: "{{ all_user }}"

    - name:  ssh directory permission
      file: path=/home/{{ item }}/.ssh/ owner={{ item }} group=ec2-user mode=0700 state=directory recurse=yes
      with_items: "{{ all_user }}"

    - name: add ssh key
      get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub dest=/home/{{ item }}/.ssh/authorized_keys force=yes
      with_items: "{{ all_user }}"

    - name: authorized_keys permission 
      file: path=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} group=ec2-user mode=0600 state=file
      with_items: "{{ all_user }}"

    - name: download source code
      git: repo=https://hangsu@bitbucket.org/realsunlab/bigdata-bootcamp.git dest=/user/share/bigdata-bootcamp update=no

    - name: copy source code
      shell: cp -R /user/share/bigdata-bootcamp /home/{{ item }}/bigdata-bootcamp
      with_items: "{{ all_user }}"

    - name: change source code owner
      file: path=/home/{{ item }}/bigdata-bootcamp state=directory owner={{ item }} group=ec2-user recurse=yes
      with_items: "{{ all_user }}"

    - name: download bigtop
      git: repo=https://github.com/apache/bigtop.git dest=/usr/share/bigtop

    - name: create vm folder
      file: path=/home/{{ item }}/vm state=directory
      become: yes
      become_user: "{{ item }}"
      with_items: "{{ all_user }}"

    - name: setup Dockerfile
      template: src=docker.tpl dest=/home/{{ item.1 }}/vm/Dockerfile owner={{ item.1 }} force=yes group=ec2-user
      with_indexed_items: "{{ all_user }}"

    - name: setup Vagrantfile
      template: src=vagrant.tpl dest=/home/{{ item }}/vm/Vagrantfile owner={{ item }} force=yes group=ec2-user
      with_items: "{{ all_user }}"

    - name: setup vagrantconfig.yaml
      copy: src=../image/vagrantconfig.yaml dest=/home/{{ item }}/vm/vagrantconfig.yaml owner={{ item }} force=yes group=ec2-user
      with_items: "{{ all_user }}"

    - name: copy start-all.sh
      template: src=start-all.sh dest=/home/{{ item }}/ owner={{ item }} force=yes group=ec2-user
      with_items: "{{ all_user }}"

    - name: make start-all.sh runable
      file: path=/home/{{ item }}/start-all.sh  mode="u+x"
      with_items: "{{ all_user }}"
