# Site
title: Bigdata Bootcamp
header-img: image/background.jpg
description: GT CSE big data bootcamp
url: "http://www.sunlab.org"
#url: "http://bigdata.manul.io"
baseurl: "/teaching/cse6250/fall2017/lab"
permalink: pretty

# Social network
#twitter_username: jimeng
#github_username: cmanul
#facebook_username: cmanul
#email: jsun@cc

# Markdown
markdown: redcarpet # kramdown #
highlighter: null#rouge

redcarpet:
  extensions: [disable_indented_code_blocks, lax_spacing, with_toc_data, prettify, footnotes, tables]

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "deploy.sh"]

# page default
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
      author: "Sun Lab"
      description: GT Big Data Bootcamp training material
